[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
extra_scripts = pre:tools/patch_esp32can.py
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  miwagner/ESP32CAN@^0.0.1
  https://github.com/h2zero/NimBLE-Arduino.git#2.5.0
build_flags =
  -I.
